name = "gleam_package_interface"
version = "1.0.0"

description = "Work with Gleam's package interfaces"
licences = ["Apache-2.0"]
repository = { type = "github", user = "gleam-lang", repo = "package-interface-decoder" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
